# Generated by Django 4.2.16 on 2026-06-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_seed_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drawhistory",
            options={"ordering": ["-drawn_at"]},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["-weight", "id"]},
        ),
        migrations.AlterField(
            model_name="drawhistory",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="drawhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draw_histories",
                to="app.user",
            ),
        ),
    ]
